name: checkin_69_auto

on:
  workflow_dispatch:  # 允许手动触发
  schedule:
    - cron: '30 12 * * *'  # 每天21:00 执行一次（UTC+8时间）

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        pip install requests beautifulsoup4 python-telegram-bot aiohttp
        
    - name: Run Python script
      run: |
        python interface_main.py
